/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnalogClock {
    }
    interface ClockHand {
        "seconds": number;
        "time": Date;
        "type": string;
    }
    interface FirstComponent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAnalogClockElement extends Components.AnalogClock, HTMLStencilElement {
    }
    var HTMLAnalogClockElement: {
        prototype: HTMLAnalogClockElement;
        new (): HTMLAnalogClockElement;
    };
    interface HTMLClockHandElement extends Components.ClockHand, HTMLStencilElement {
    }
    var HTMLClockHandElement: {
        prototype: HTMLClockHandElement;
        new (): HTMLClockHandElement;
    };
    interface HTMLFirstComponentElement extends Components.FirstComponent, HTMLStencilElement {
    }
    var HTMLFirstComponentElement: {
        prototype: HTMLFirstComponentElement;
        new (): HTMLFirstComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "analog-clock": HTMLAnalogClockElement;
        "clock-hand": HTMLClockHandElement;
        "first-component": HTMLFirstComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AnalogClock {
    }
    interface ClockHand {
        "seconds"?: number;
        "time"?: Date;
        "type"?: string;
    }
    interface FirstComponent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "analog-clock": AnalogClock;
        "clock-hand": ClockHand;
        "first-component": FirstComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "analog-clock": LocalJSX.AnalogClock & JSXBase.HTMLAttributes<HTMLAnalogClockElement>;
            "clock-hand": LocalJSX.ClockHand & JSXBase.HTMLAttributes<HTMLClockHandElement>;
            "first-component": LocalJSX.FirstComponent & JSXBase.HTMLAttributes<HTMLFirstComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
